export const WORK_REPORT_CLIENT_CSS = String.raw`
.telosReportSettings{box-sizing:border-box;width:100%;height:100%;overflow:auto;padding:6px 0 36px;color:var(--dsw-alias-label-primary)}
.telosReportHeader,.telosReportPanelHeader{display:flex;align-items:flex-start;justify-content:space-between;gap:18px}.telosReportHeader{margin-bottom:18px}.telosReportHeader h1,.telosReportPanel h2{margin:0 0 5px;font-size:18px}.telosReportHeader p,.telosReportPanelHeader p{max-width:760px;margin:0;color:var(--dsw-alias-label-tertiary);font-size:12px;line-height:1.6}
.telosReportSettings button{min-height:32px;padding:5px 11px;border:1px solid var(--dsw-alias-border-l1);border-radius:8px;background:var(--dsw-alias-bg-layer-2);color:inherit;cursor:pointer}.telosReportSettings button[data-primary]{border-color:transparent;background:var(--dsw-alias-brand-primary);color:#fff}.telosReportSettings button[data-danger]{color:var(--dsw-alias-state-error-primary)}.telosReportSettings button:disabled{cursor:not-allowed;opacity:.5}
.telosReportBanner,.telosReportEmpty{margin-bottom:14px;padding:11px 13px;border-radius:9px;background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-label-secondary);font-size:12px;line-height:1.55}.telosReportBanner[data-error]{color:var(--dsw-alias-state-error-primary)}
.telosReportSummary{display:flex;align-items:center;gap:18px;margin-bottom:16px;padding:12px 14px;border:1px solid var(--dsw-alias-border-l1);border-radius:10px}.telosReportSummary span{font-size:12px}.telosReportSummary strong{font-size:16px}.telosReportSummary small{min-width:0;margin-left:auto;overflow:hidden;color:var(--dsw-alias-label-tertiary);font-size:10px;text-overflow:ellipsis;white-space:nowrap}
.telosReportPanel{margin-top:16px;padding:18px;border:1px solid var(--dsw-alias-border-l1);border-radius:12px;background:var(--dsw-alias-bg-layer-1)}.telosReportPanelHeader{margin-bottom:14px}.telosReportGrid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.telosReportMailGrid{grid-template-columns:2fr .7fr 1.4fr 1fr 1.4fr 1.4fr}.telosReportPanel label{display:grid;gap:6px;color:var(--dsw-alias-label-secondary);font-size:12px}.telosReportPanel label small{color:var(--dsw-alias-label-tertiary);font-size:10px}.telosReportPanel input,.telosReportPanel textarea{box-sizing:border-box;width:100%;min-height:36px;padding:8px 10px;border:1px solid var(--dsw-alias-border-l1);border-radius:8px;background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-label-primary);font:inherit}.telosReportPanel textarea{resize:vertical;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;line-height:1.6}
.telosReportTabs{display:flex;gap:7px;margin-bottom:12px}.telosReportTabs button[data-active]{border-color:var(--dsw-alias-brand-primary);color:var(--dsw-alias-brand-primary)}.telosReportActions{display:flex;justify-content:flex-end;gap:8px;margin-top:12px}.telosReportCheckbox{display:flex!important;grid-template-columns:auto 1fr!important;align-items:center;margin-top:12px}.telosReportCheckbox input{width:auto!important;min-height:auto!important}.telosReportStatus{flex:none;padding:5px 8px;border-radius:999px;background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-label-tertiary);font-size:10px}.telosReportStatus[data-ready]{color:var(--dsw-alias-state-success-primary)}
.telosReportSubsection{margin-top:14px;padding-top:3px;border-top:1px solid var(--dsw-alias-border-l1)}.telosReportImapGrid{grid-template-columns:1.5fr .6fr 1.3fr 1.4fr;margin-top:12px}.telosReportInlineOptions{display:flex;flex-wrap:wrap;gap:22px}.telosReportImapPassword{max-width:420px;margin-top:12px}.telosReportHint{margin:9px 0 0;color:var(--dsw-alias-label-tertiary);font-size:10px}
.telosReportDeliveryList{border-top:1px solid var(--dsw-alias-border-l1)}.telosReportDelivery{display:grid;grid-template-columns:minmax(220px,1.4fr) minmax(180px,1fr) minmax(150px,.8fr);gap:18px;align-items:center;min-height:62px;border-bottom:1px solid var(--dsw-alias-border-l1)}.telosReportDelivery strong,.telosReportDelivery span{display:block;font-size:12px}.telosReportDelivery small{display:block;margin-top:4px;overflow:hidden;color:var(--dsw-alias-label-tertiary);font-size:10px;text-overflow:ellipsis;white-space:nowrap}.telosReportDelivery [data-sync=synced]{color:var(--dsw-alias-state-success-primary)}.telosReportDelivery [data-sync=failed]{color:var(--dsw-alias-state-error-primary)}
@media(max-width:1100px){.telosReportMailGrid,.telosReportImapGrid{grid-template-columns:1fr 1fr}}@media(max-width:760px){.telosReportGrid,.telosReportMailGrid,.telosReportImapGrid,.telosReportDelivery{grid-template-columns:1fr}.telosReportDelivery{gap:8px;padding:12px 0}.telosReportSummary{flex-wrap:wrap}.telosReportSummary small{width:100%;margin-left:0}}
`

export function installWorkReportStyles(): () => void {
  const style = document.createElement('style')
  style.dataset.telosWorkReport = 'true'
  style.textContent = WORK_REPORT_CLIENT_CSS
  document.head.append(style)
  return () => style.remove()
}
