export const IPC_CHANNELS = {
  appInfo: 'telos:system:get-app-info',
  dshWebStatus: 'telos:dsh-web:get-status',
  dshWebRetry: 'telos:dsh-web:retry',
  dshWebState: 'telos:dsh-web:state',
  runtimeStatus: 'telos:runtime:get-status',
  runtimeRun: 'telos:runtime:run',
  runtimeEvent: 'telos:runtime:event',
  workbenchEditorPanelsGet: 'telos:workbench:get-editor-panels',
  workbenchEditorPanelsSet: 'telos:workbench:set-editor-panels',
  companionState: 'telos:companion:state',
  companionConfig: 'telos:companion:config',
  companionMenu: 'telos:companion:menu',
  companionRendererError: 'telos:companion:renderer-error',
  companionSettingsGet: 'telos:companion:settings:get',
  companionSettingsUpdate: 'telos:companion:settings:update',
  companionSettingsImport: 'telos:companion:settings:import',
  companionSettingsRemove: 'telos:companion:settings:remove',
  companionSettingsChanged: 'telos:companion:settings:changed',
} as const
