import { cpSync, existsSync, mkdirSync, renameSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'

const PATCH_FILENAME = 'telos.web.patch.yml'
const TELOS_SIDEBAR_PACKAGE = '@telos/dsh-client-ui-sidebar'

/** Render the fail-loud DSH patch that swaps only the sidebar presentation plugin. */
export function renderTelosDshWebPatch(): string {
  return [
    '# Generated by TELOS. DSH remains the source of all non-overridden Web rows.',
    '- id: ui-sidebar',
    '  disabled: true',
    '- insert:',
    '    - id: telos-ui-sidebar',
    `      name: ${JSON.stringify(TELOS_SIDEBAR_PACKAGE)}`,
    '',
  ].join('\n')
}

/** Materialize the absolute-path overlay in TELOS-owned application data. */
export function prepareTelosDshWebPatch(dshHome: string, sidebarPackageRoot: string): string {
  const packageManifest = join(sidebarPackageRoot, 'package.json')
  const clientBundle = join(sidebarPackageRoot, 'lib/client.js')
  if (!existsSync(packageManifest) || !existsSync(clientBundle)) {
    throw new Error('TELOS DSH sidebar overlay is missing; run pnpm dsh:build')
  }

  const installedPackageRoot = join(dshHome, 'profiles/node_modules/@telos/dsh-client-ui-sidebar')
  rmSync(installedPackageRoot, { recursive: true, force: true })
  mkdirSync(dirname(installedPackageRoot), { recursive: true })
  cpSync(sidebarPackageRoot, installedPackageRoot, { recursive: true, force: true })

  mkdirSync(dshHome, { recursive: true })
  const path = join(dshHome, PATCH_FILENAME)
  const temporaryPath = `${path}.${String(process.pid)}.tmp`
  writeFileSync(temporaryPath, renderTelosDshWebPatch(), { mode: 0o600 })
  try {
    renameSync(temporaryPath, path)
  } catch {
    // Windows cannot atomically replace an existing destination.
    rmSync(path, { force: true })
    renameSync(temporaryPath, path)
  }
  return path
}
