export const MULTI_ROOT_WORKSPACE_CSS = String.raw`
.telosWorkspaceFlowBackdrop{position:fixed;inset:0;z-index:10000;display:grid;place-items:center;padding:24px;background:color-mix(in srgb,#000 30%,transparent);backdrop-filter:blur(4px)}
.telosWorkspaceFlow{box-sizing:border-box;width:min(620px,100%);max-height:min(760px,calc(100vh - 48px));overflow:auto;padding:24px;border:1px solid var(--dsw-alias-border-l1);border-radius:18px;background:var(--dsw-alias-bg-layer-1);box-shadow:0 24px 80px rgba(0,0,0,.22);color:var(--dsw-alias-label-primary)}
.telosWorkspaceFlow header{display:flex;align-items:flex-start;justify-content:space-between;gap:20px}.telosWorkspaceFlow h2{margin:0;font-size:20px;line-height:1.35}.telosWorkspaceFlow header p{margin:6px 0 0;color:var(--dsw-alias-label-tertiary);font-size:12px;line-height:1.6}.telosWorkspaceFlow button{border:1px solid var(--dsw-alias-border-l1);border-radius:9px;background:var(--dsw-alias-bg-layer-2);color:inherit;font:inherit;cursor:pointer}.telosWorkspaceFlow button:disabled{cursor:not-allowed;opacity:.48}.telosWorkspaceFlowClose{width:32px;height:32px;padding:0;font-size:22px;line-height:1}
.telosWorkspaceFlowName{display:grid;gap:8px;margin-top:24px;font-size:12px;font-weight:600}.telosWorkspaceFlowName input{box-sizing:border-box;width:100%;height:42px;padding:0 12px;border:1px solid var(--dsw-alias-border-l1);border-radius:10px;outline:none;background:var(--dsw-alias-bg-layer-2);color:inherit;font:inherit}.telosWorkspaceFlowName input:focus{border-color:var(--dsw-alias-brand-primary);box-shadow:0 0 0 3px color-mix(in srgb,var(--dsw-alias-brand-primary) 16%,transparent)}
.telosWorkspaceFlowRoots{margin-top:22px}.telosWorkspaceFlowRootsTitle{display:flex;align-items:baseline;justify-content:space-between;gap:14px;margin-bottom:9px;font-size:12px;font-weight:600}.telosWorkspaceFlowRootsTitle small{color:var(--dsw-alias-label-tertiary);font-weight:400}.telosWorkspaceFlowEmpty{display:grid;width:100%;min-height:132px;place-content:center;gap:7px;border-style:dashed!important}.telosWorkspaceFlowEmpty strong{font-size:13px}.telosWorkspaceFlowEmpty span{color:var(--dsw-alias-label-tertiary);font-size:11px}
.telosWorkspaceFlowRootList{display:grid;gap:8px}.telosWorkspaceFlowRoot{display:grid;grid-template-columns:26px minmax(0,1fr) auto auto;align-items:center;gap:10px;padding:10px;border:1px solid var(--dsw-alias-border-l1);border-radius:10px;background:var(--dsw-alias-bg-layer-2)}.telosWorkspaceFlowFolderIcon{font-size:20px}.telosWorkspaceFlowRoot>span:nth-child(2){display:grid;min-width:0;gap:3px}.telosWorkspaceFlowRoot strong,.telosWorkspaceFlowRoot small{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.telosWorkspaceFlowRoot strong{font-size:12px}.telosWorkspaceFlowRoot small{color:var(--dsw-alias-label-tertiary);font-size:10px}.telosWorkspaceFlowRoot em{padding:3px 7px;border-radius:999px;background:color-mix(in srgb,var(--dsw-alias-brand-primary) 12%,transparent);color:var(--dsw-alias-brand-primary);font-size:10px;font-style:normal}.telosWorkspaceFlowRoot button{padding:5px 8px;border-color:transparent;background:transparent;color:var(--dsw-alias-label-tertiary);font-size:11px}.telosWorkspaceFlowAdd{min-height:38px;border-style:dashed!important}
.telosWorkspaceFlowError{margin:12px 0 0;color:var(--dsw-alias-state-error-primary);font-size:11px}.telosWorkspaceFlow footer{display:flex;justify-content:flex-end;gap:8px;margin-top:24px}.telosWorkspaceFlow footer button{min-width:88px;min-height:38px;padding:6px 14px}.telosWorkspaceFlow footer button[data-primary]{border-color:transparent;background:var(--dsw-alias-brand-primary);color:#fff}
@media(max-width:640px){.telosWorkspaceFlowBackdrop{padding:12px}.telosWorkspaceFlow{padding:18px;border-radius:14px}.telosWorkspaceFlowRootsTitle{align-items:flex-start;flex-direction:column;gap:3px}.telosWorkspaceFlowRoot{grid-template-columns:24px minmax(0,1fr) auto}.telosWorkspaceFlowRoot em{display:none}.telosWorkspaceFlow footer button{flex:1}}
`

export function installMultiRootWorkspaceStyles(): () => void {
  const style = document.createElement('style')
  style.dataset.telosMultiRootWorkspace = 'true'
  style.textContent = MULTI_ROOT_WORKSPACE_CSS
  document.head.append(style)
  return () => style.remove()
}
